
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '11.0'
use_frameworks!

  target 'OrderNow' do
	pod 'SnapKit', '~> 5.0.0'
	pod 'FacebookCore'
	pod 'FacebookLogin'
	pod 'FacebookShare'
	pod 'GoogleSignIn'
  pod 'Firebase/Analytics'
  pod 'Firebase/Database'
	pod 'GoogleMaps'
	pod 'GooglePlaces'
  pod 'WWLayout'
end
