source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'

  target 'OrderNow' do
    pod 'SnapKit', '~> 5.0.0'
    pod 'FacebookCore'
    pod 'GoogleSignIn'
    pod 'FacebookLogin'
    pod 'FacebookShare'
    
end
