# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OrderNow' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'WWLayout', '~>0.5.5'
  pod 'Firebase/Analytics'
  pod 'Firebase/Database'
  # Pods for OrderNow


end
